apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ls5-jan292026-gitops
  description: GitOps manifest for Llama Stack Agentic - ls5-jan292026   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=ls5-jan292026
    janus-idp.io/tekton: ls5-jan292026 
    backstage.io/kubernetes-id: ls5-jan292026 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ls5-jan292026  

