# RBAC resources for Kubernetes MCP Server
# The MCP Server needs read access to Kubernetes resources to provide
# cluster introspection tools to the AI agents
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ls5-jan292026-mcp-sa
  labels:
    app.kubernetes.io/instance: ls5-jan292026
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ls5-jan292026-mcp-sa
    app.kubernetes.io/component: mcp-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ls5-jan292026-mcp-reader
  labels:
    app.kubernetes.io/instance: ls5-jan292026
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ls5-jan292026-mcp-reader
rules:
  # Core resources - read-only access
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/log
      - services
      - events
      - configmaps
      - secrets
      - persistentvolumeclaims
      - nodes
      - endpoints
      - replicationcontrollers
    verbs: ["get", "list", "watch"]
  # Apps resources - read-only access
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]
  # Batch resources - read-only access
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  # Networking resources - read-only access
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch"]
  # OpenShift routes - read-only access
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs: ["get", "list", "watch"]
  # Metrics - read-only access
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ls5-jan292026-mcp-reader-binding
  labels:
    app.kubernetes.io/instance: ls5-jan292026
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ls5-jan292026-mcp-reader
subjects:
  - kind: ServiceAccount
    name: ls5-jan292026-mcp-sa
    namespace: hello

