# Route for Streamlit UI Application (OpenShift)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: ls5-jan292026
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ls5-jan292026
  name: ls5-jan292026
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ls5-jan292026
    weight: 100
  wildcardPolicy: None

